services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    restart: unless-stopped
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.config.file=/etc/prometheus/web.yml
    volumes:
      - ./prometheus:/etc/prometheus
      - prom-data:/prometheus      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=temp-gr@f@n@-p@$$w0rd
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:  
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
volumes: 
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs: